#!/bin/bash

### BEGIN INIT INFO
# Provides:          hobot
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: load wifi driver
### END INIT INFO

do_load_wifi()
{
	som_name=$(cat /sys/class/socinfo/som_name)
	if [ ${som_name} == '5' ];then
		modprobe bcmdhd
	elif [ ${som_name} == '6' ];then
		modprobe 8723ds
	elif [ ${som_name} == '8' ];then
		modprobe 8821cs
	fi
}

case "$1" in
	start)
		do_load_wifi
		exit 0
		;;
	*)
		echo "Usage: $0 start"
		exit 0
	;;
esac
